### ISSUE TITLE
eb_user vs. ls2

### ISSUE THREAD

**Issue by bmcgough** [FredHutch/EBcb#1]
It is a bit confusing that eb_user is the suggested (required?) username, but the default directory is /home/ls2. It looks like /home/eb_user is $HOME, but a vanilla `docker exec` lands you in /home/ls2.

**Comment by bmcgough** [comment]
And /home/ls2 is owned by root. Where/how do I bring in a new easyconfig to build?

**Comment by fizwit** [comment]
Finally!  A new smaller EBcb container.  Built with foss-2019b and EB 4.3.1 the finished size is 2.72GB.  2.4GB is the /eb volume which contains EB and foss-2019b toolchain.  EBcb is built with a single Dockefile utilizing multi-stage build. 
- /ls2 and sources have been removed from the container to make it smaller
- eb_user home is /home/eb_user 

I also suggest sudo too eb_user with the environment.  /etc/profile.d will setup LMOD and load EasyBuild.

```sudo su - eb_user```

commit #307d6f8
